version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - AWS_REGION=ap-southeast-2
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - DYNAMODB_TABLE=dev-tinyurl-table
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - dynamodb

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  redis_data:
  dynamodb_data: 